"""Added path column

Revision ID: 39fea8647180
Revises: f91a8beb8472
Create Date: 2023-07-29 14:37:39.341128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39fea8647180'
down_revision = 'f91a8beb8472'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'path')
    # ### end Alembic commands ###
